# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/oousterm/Documents/GitHub/CPE-233/CPE_233_Olive and Andrew/CPE_233_Olive and Andrew.cache/wt} [current_project]
set_property parent.project_path {C:/Users/oousterm/Documents/GitHub/CPE-233/CPE_233_Olive and Andrew/CPE_233_Olive and Andrew.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/oousterm/Documents/GitHub/CPE-233/CPE_233_Olive and Andrew/CPE_233_Olive and Andrew.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/oousterm/Documents/GitHub/CPE-233/CPE_233_Olive and Andrew/CPE_233_Olive and Andrew.srcs/sources_1/new/Comarator_GT.vhd}
  {C:/Users/oousterm/Documents/GitHub/CPE-233/CPE_233_Olive and Andrew/CPE_233_Olive and Andrew.srcs/sources_1/new/Counter_4Bit.vhd}
  {C:/Users/oousterm/Documents/GitHub/CPE-233/CPE_233_Olive and Andrew/CPE_233_Olive and Andrew.srcs/sources_1/new/FSM_Exp1.vhd}
  {C:/Users/oousterm/Documents/GitHub/CPE-233/CPE_233_Olive and Andrew/CPE_233_Olive and Andrew.srcs/sources_1/new/MUX_2x1.vhd}
  {C:/Users/oousterm/Documents/GitHub/CPE-233/CPE_233_Olive and Andrew/CPE_233_Olive and Andrew.srcs/sources_1/new/MUX_4x1.vhd}
  {C:/Users/oousterm/Documents/GitHub/CPE-233/CPE_233_Olive and Andrew/CPE_233_Olive and Andrew.srcs/sources_1/new/RAM_16x8.vhd}
  {C:/Users/oousterm/Documents/GitHub/CPE-233/CPE_233_Olive and Andrew/CPE_233_Olive and Andrew.srcs/sources_1/new/RCA_5Bit.vhd}
  {C:/Users/oousterm/Documents/GitHub/CPE-233/CPE_233_Olive and Andrew/CPE_233_Olive and Andrew.srcs/sources_1/new/ROM_Exp1.vhd}
  {C:/Users/oousterm/Documents/GitHub/CPE-233/CPE_233_Olive and Andrew/CPE_233_Olive and Andrew.srcs/sources_1/new/Register_8Bit.vhd}
  {C:/Users/oousterm/Documents/GitHub/CPE-233/CPE_233_Olive and Andrew/CPE_233_Olive and Andrew.srcs/sources_1/new/clk_div_fs.vhd}
  {C:/Users/oousterm/Documents/GitHub/CPE-233/CPE_233_Olive and Andrew/CPE_233_Olive and Andrew.srcs/sources_1/new/sseg_dec_uni.vhd}
  {C:/Users/oousterm/Documents/GitHub/CPE-233/CPE_233_Olive and Andrew/CPE_233_Olive and Andrew.srcs/sources_1/new/Exp1_Main.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top Exp1_Main -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Exp1_Main.dcp

catch { report_utilization -file Exp1_Main_utilization_synth.rpt -pb Exp1_Main_utilization_synth.pb }
