# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a50tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/oousterm/Documents/GitHub/CPE-233/Lab_05/Lab_05.cache/wt [current_project]
set_property parent.project_path C:/Users/oousterm/Documents/GitHub/CPE-233/Lab_05/Lab_05.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/oousterm/Documents/GitHub/CPE-233/Lab_05/Lab_05.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/oousterm/Documents/GitHub/CPE-233/Lab_05/Lab_05.srcs/sources_1/new/CLK_reducer.vhd
  C:/Users/oousterm/Documents/GitHub/CPE-233/Lab_05/Lab_05.srcs/sources_1/new/Comparator_GT.vhd
  C:/Users/oousterm/Documents/GitHub/CPE-233/Lab_05/Lab_05.srcs/sources_1/new/Counter_4Bit.vhd
  C:/Users/oousterm/Documents/GitHub/CPE-233/Lab_05/Lab_05.srcs/sources_1/new/Dual_Port_Ram.vhd
  C:/Users/oousterm/Documents/GitHub/CPE-233/Lab_05/Lab_05.srcs/sources_1/new/FSM_LAB_5.vhd
  C:/Users/oousterm/Documents/GitHub/CPE-233/Lab_05/Lab_05.srcs/sources_1/new/Mux_2x1.vhd
  C:/Users/oousterm/Documents/GitHub/CPE-233/Lab_05/Lab_05.srcs/sources_1/new/Mux_4x1.vhd
  C:/Users/oousterm/Documents/GitHub/CPE-233/Lab_05/Lab_05.srcs/sources_1/new/RCA_4Bit.vhd
  C:/Users/oousterm/Documents/GitHub/CPE-233/Lab_05/Lab_05.srcs/sources_1/new/ROM.vhd
  C:/Users/oousterm/Documents/GitHub/CPE-233/Lab_05/Lab_05.srcs/sources_1/new/Register_8Bit.vhd
  C:/Users/oousterm/Documents/GitHub/CPE-233/Lab_05/Lab_05.srcs/sources_1/new/SSEG_DISPLAY.vhd
  C:/Users/oousterm/Documents/GitHub/CPE-233/Lab_05/Lab_05.srcs/sources_1/new/Lab_5_Main.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top Lab_5_Main -part xc7a50tcsg324-1


write_checkpoint -force -noxdef Lab_5_Main.dcp

catch { report_utilization -file Lab_5_Main_utilization_synth.rpt -pb Lab_5_Main_utilization_synth.pb }
